# Generated by Django 4.1.4 on 2022-12-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ("-date_issued",), "verbose_name_plural": "equipment"},
        ),
    ]
