# Generated by Django 4.1.4 on 2022-12-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_category_options_alter_equipment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={"ordering": ("name",)},
        ),
    ]
